on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          path: .
          config-file: release-please-config.json

  build-jar:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Find built JAR file
        id: find_jar
        run: |
          JAR_PATH=$(find target -type f -name 'ProjektSE-assembly-*.jar' | head -n 1)
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

      - name: Rename JAR with release version
        run: |
          mv "$JAR_PATH" "target/scala-$(echo $JAR_PATH | grep -oP 'scala-\K[0-9\.]+')/ProjektSE-${{ needs.release-please.outputs.tag_name }}.jar"
          echo "RENAMED_JAR=target/scala-$(echo $JAR_PATH | grep -oP 'scala-\K[0-9\.]+')/ProjektSE-${{ needs.release-please.outputs.tag_name }}.jar" >> $GITHUB_ENV

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: ${{ env.RENAMED_JAR }}
