on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          path: .
          config-file: release-please-config.json
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        run: sbt assembly
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: projektse-jar
          path: target/scala-3.5.1/ProjektSE-assembly-0.1.0-SNAPSHOT.jar
          
